import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7f4ef',
  },
  screenContentWrapper: {
    flex: 1,
  },
  bottomNavScreen: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavScreenTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#2c1f0c',
    marginBottom: 12,
  },
  bottomNavScreenSubtitle: {
    fontSize: 16,
    color: '#6f5a35',
    lineHeight: 24,
    textAlign: 'center',
  },
  authContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 32,
    justifyContent: 'center',
  },
  authIntro: {
    marginBottom: 36,
  },
  authGreeting: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6f5a35',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  authName: {
    fontSize: 42,
    fontWeight: '700',
    color: '#2c1f0c',
    marginTop: 8,
  },
  authSubtitle: {
    fontSize: 16,
    color: '#6f5a35',
    lineHeight: 24,
    marginTop: 12,
  },
  authActions: {
    flexDirection: 'column',
    marginTop: 12,
  },
  authPrimaryButton: {
    borderRadius: 18,
    backgroundColor: '#3b2a15',
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  authPrimaryButtonDisabled: {
    opacity: 0.7,
  },
  authPrimaryButtonLabel: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  authSecondaryButton: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f7f0e3',
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authSecondaryButtonLabel: {
    color: '#3b2a15',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  authFormContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  authFormTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2c1f0c',
    marginBottom: 8,
  },
  authFormSubtitle: {
    fontSize: 14,
    color: '#6f5a35',
    lineHeight: 20,
    marginBottom: 20,
  },
  authErrorText: {
    fontSize: 14,
    color: '#9b2c2c',
    marginBottom: 12,
  },
  authInput: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 14,
    backgroundColor: '#fffdf8',
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c1f0c',
    marginBottom: 12,
  },
  authPasswordInputContainer: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 14,
    backgroundColor: '#fffdf8',
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 6,
    marginBottom: 12,
  },
  authPasswordInput: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c1f0c',
  },
  authPasswordToggle: {
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  homeContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  homeHeader: {
    marginBottom: 20,
  },
  homeHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeHeaderActions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    marginTop: 12,
  },
  iconButtonContainer: {
    marginLeft: 12,
    alignItems: 'center',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f7f0e3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeActionButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f7f0e3',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 18,
    marginBottom: 12,
  },
  homeActionButtonSpacing: {
    marginRight: 12,
  },
  homeActionLabel: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '600',
    color: '#3b2a15',
    textAlign: 'center',
    lineHeight: 18,
  },
  iconBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    minWidth: 18,
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 9,
    backgroundColor: '#c86148',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBadgeLabel: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 0,
    color: '#2c1f0c',
  },
  homeList: {
    flex: 1,
    marginTop: 20,
  },
  homeListContent: {
    paddingBottom: 20,
  },
  homeListEmpty: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeCard: {
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d7c5a8',
    marginBottom: 12,
  },
  homeCardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c1f0c',
  },
  homeCardSubtitle: {
    fontSize: 14,
    color: '#6f5a35',
    marginTop: 4,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  topBarRightAccessory: {
    minWidth: 44,
    alignItems: 'flex-end',
  },
  topBarRightPlaceholder: {
    width: 44,
    height: 44,
  },
  topBarTitleOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#3b2a15',
  },
  screenSurface: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    padding: 20,
  },
  sectionScreenSurface: {
    paddingHorizontal: 0,
    paddingTop: 12,
    paddingBottom: 0,
    borderRadius: 0,
  },
  backButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f0e4d2',
  },
  backButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButtonIcon: {
    marginRight: 6,
  },
  backButtonLabel: {
    fontSize: 15,
    fontWeight: '500',
    color: '#3b2a15',
  },
  shareBackIconButton: {
    padding: 8,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f0e4d2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailSubtitle: {
    fontSize: 16,
    color: '#6f5a35',
    marginTop: -4,
    marginBottom: 20,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 14,
    backgroundColor: '#fffaf3',
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#3b2a15',
    marginBottom: 12,
  },
  searchDivider: {
    borderBottomWidth: 1,
    borderColor: '#e6d9c4',
    marginBottom: 16,
  },
  searchResultCount: {
    fontSize: 13,
    color: '#6f5a35',
    marginBottom: 12,
  },
  searchResultsList: {
    flex: 1,
  },
  searchResultsListContent: {
    paddingBottom: 24,
  },
  searchResultCard: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 16,
    padding: 14,
    backgroundColor: '#f7f0e3',
    marginBottom: 12,
  },
  searchResultTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c1f0c',
  },
  searchResultWriting: {
    fontSize: 14,
    color: '#6f5a35',
    marginTop: 4,
  },
  searchResultPreview: {
    fontSize: 14,
    color: '#3b2a15',
    marginTop: 10,
  },
  searchHighlightText: {
    backgroundColor: '#f4d98a',
    borderRadius: 4,
    paddingHorizontal: 2,
  },
  recentSearchesWrapper: {
    paddingTop: 8,
  },
  recentSearchHeading: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6f5a35',
    marginBottom: 10,
  },
  recentSearchChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  recentSearchChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f7f0e3',
    marginRight: 8,
    marginBottom: 8,
  },
  recentSearchChipLabel: {
    fontSize: 14,
    color: '#3b2a15',
  },
  sectionList: {
    flex: 1,
  },
  sectionListContent: {
    paddingBottom: 16,
  },
  sectionRow: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f7f0e3',
    marginBottom: 12,
  },
  sectionRowTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#3b2a15',
  },
  sectionRowDescription: {
    fontSize: 14,
    color: '#6f5a35',
    marginTop: 4,
  },
  sectionHeader: {
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  sectionHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  passageMeta: {
    marginBottom: 12,
  },
  passageMetaHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  passageMetaInfo: {
    flex: 1,
    paddingRight: 12,
  },
  passageGroup: {
    marginBottom: 24,
  },
  passageMetaLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6f5a35',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  passageMetaWriting: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000000',
    marginTop: 4,
  },
  passageMetaSection: {
    fontSize: 16,
    color: '#4a4a4a',
    marginTop: 2,
  },
  programList: {
    flex: 1,
    marginTop: 16,
  },
  programListContent: {
    paddingBottom: 32,
  },
  programStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 12,
  },
  programStepItem: {
    alignItems: 'center',
    marginHorizontal: 4,
  },
  programStepNode: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#d7c5a8',
    backgroundColor: '#fffaf3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  programStepNodeCompleted: {
    borderColor: '#6d9c7c',
    backgroundColor: '#6d9c7c',
  },
  programStepNodeActive: {
    borderColor: '#3b2a15',
  },
  programStepNodeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#b8a58b',
  },
  programStepNodeLabelActive: {
    color: '#fffaf3',
  },
  programStepLabel: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '600',
    color: '#6f5a35',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  programStepLabelActive: {
    color: '#3b2a15',
  },
  programStepConnector: {
    flex: 1,
    height: 2,
    backgroundColor: '#e0d2bd',
    marginHorizontal: 8,
  },
  programStepConnectorCompleted: {
    backgroundColor: '#6d9c7c',
  },
  programStepSection: {
    width: '100%',
  },
  programPassageList: {
    marginTop: 12,
  },
  programStepControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 12,
  },
  programStepControlButton: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#fffaf3',
  },
  programStepControlButtonPrimary: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    backgroundColor: '#3b2a15',
  },
  programStepControlLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3b2a15',
  },
  programStepControlPrimaryLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fffaf3',
  },
  myVersesList: {
    flex: 1,
    marginTop: 16,
  },
  myVersesListContent: {
    paddingBottom: 32,
  },
  programThemeSection: {
    paddingHorizontal: 4,
    paddingBottom: 24,
  },
  programThemeTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c1f0c',
    marginBottom: 8,
  },
  programThemeDescription: {
    fontSize: 14,
    color: '#6f5a35',
    marginBottom: 12,
  },
  programThemeButton: {
    alignSelf: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#c6a87d',
    backgroundColor: '#f5e9d6',
  },
  programThemeButtonLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#3b2a15',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  programThemeFeedback: {
    fontSize: 13,
    color: '#6f5a35',
    marginTop: 12,
  },
  programForm: {
    paddingHorizontal: 4,
    paddingBottom: 24,
  },
  programFormTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c1f0c',
    marginBottom: 8,
  },
  programFormHint: {
    fontSize: 14,
    color: '#6f5a35',
    marginBottom: 16,
  },
  programFieldRow: {
    flexDirection: 'row',
    columnGap: 12,
  },
  programFieldColumn: {
    flex: 1,
  },
  programInputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3b2a15',
    marginBottom: 6,
  },
  programHelperText: {
    fontSize: 12,
    color: '#8a7752',
    marginTop: -8,
    marginBottom: 12,
  },
  programPickerInput: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    backgroundColor: '#fffaf3',
    justifyContent: 'center',
    marginBottom: 16,
  },
  programPickerValue: {
    fontSize: 16,
    color: '#3b2a15',
  },
  programPickerPlaceholder: {
    fontSize: 16,
    color: '#b8a58b',
  },
  programInputError: {
    fontSize: 12,
    color: '#a83c38',
    marginTop: -8,
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  programTextInput: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#fffaf3',
    fontSize: 16,
    color: '#3b2a15',
    marginBottom: 16,
  },
  programTextArea: {
    minHeight: 96,
  },
  programFrequencyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 8,
    rowGap: 8,
    marginBottom: 16,
  },
  programFrequencyChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#fffaf3',
  },
  programFrequencyChipActive: {
    backgroundColor: '#3b2a15',
    borderColor: '#3b2a15',
  },
  programFrequencyChipLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3b2a15',
  },
  programFrequencyChipLabelActive: {
    color: '#fffaf3',
  },
  programFacilitatorChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  programFacilitatorChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: '#f0e4d2',
  },
  programFacilitatorChipLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3b2a15',
  },
  programFacilitatorChipRemove: {
    marginLeft: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 12,
    backgroundColor: '#e3d4bd',
  },
  programFacilitatorChipRemoveLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#5a3d1d',
  },
  programFacilitatorChipRestore: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#fffaf3',
    marginBottom: 8,
  },
  programFacilitatorChipRestoreLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3b2a15',
  },
  programPickerModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    padding: 24,
  },
  programPickerModalCard: {
    borderRadius: 20,
    backgroundColor: '#fffaf3',
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignSelf: 'stretch',
  },
  programPickerModalWheel: {
    width: '100%',
    height: 220,
  },
  programPickerModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    columnGap: 12,
    marginTop: 12,
  },
  programPickerModalButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: '#f0e4d2',
  },
  programPickerModalButtonPrimary: {
    backgroundColor: '#3b2a15',
  },
  programPickerModalButtonLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3b2a15',
  },
  programPickerModalButtonPrimaryLabel: {
    color: '#fffaf3',
  },
  programRemoveButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f0e4d2',
  },
  programRemoveLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#3b2a15',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  programClearButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f7f0e3',
  },
  programClearLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#3b2a15',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  programActions: {
    paddingVertical: 24,
    alignItems: 'stretch',
  },
  programActionButton: {
    alignSelf: 'stretch',
    marginBottom: 16,
  },
  submitButton: {
    alignSelf: 'stretch',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 18,
    backgroundColor: '#6d9c7c',
    borderWidth: 1,
    borderColor: '#598467',
    alignItems: 'center',
  },
  submitButtonLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  programStatusError: {
    fontSize: 14,
    color: '#b04b3c',
    textAlign: 'center',
    marginTop: 4,
  },
  programStatusSuccess: {
    fontSize: 14,
    color: '#3a7a5a',
    textAlign: 'center',
    marginTop: 4,
  },
  programModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(43, 27, 10, 0.6)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  programModalCard: {
    backgroundColor: '#fffaf3',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    padding: 20,
    maxHeight: '90%',
  },
  programModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c1f0c',
    marginBottom: 6,
  },
  programModalDescription: {
    fontSize: 14,
    color: '#6f5a35',
    marginBottom: 16,
  },
  programModalInput: {
    marginBottom: 12,
  },
  programModalSearchRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 12,
  },
  programModalButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#c6a87d',
    backgroundColor: '#f0e4d2',
  },
  programModalButtonLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3b2a15',
  },
  programModalMessage: {
    fontSize: 14,
    color: '#6f5a35',
    marginBottom: 12,
  },
  programModalResults: {
    flexGrow: 0,
    marginBottom: 16,
  },
  programModalResultsContent: {
    paddingBottom: 4,
  },
  programModalResult: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 16,
    padding: 14,
    backgroundColor: '#f7f0e3',
    marginBottom: 12,
  },
  programModalResultSelected: {
    borderColor: '#6d9c7c',
    backgroundColor: '#e9f3ec',
  },
  programModalResultTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c1f0c',
  },
  programModalResultWriting: {
    fontSize: 14,
    color: '#6f5a35',
    marginTop: 4,
  },
  programModalResultPreview: {
    fontSize: 14,
    color: '#3b2a15',
    marginTop: 8,
  },
  programModalResultToggle: {
    fontSize: 12,
    color: '#6f5a35',
    marginTop: 10,
  },
  programModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  programModalActionSpacing: {
    marginLeft: 12,
  },
  programModalButtonPrimary: {
    backgroundColor: '#6d9c7c',
    borderColor: '#598467',
  },
  programModalButtonPrimaryLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },
  secondaryButton: {
    alignSelf: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#c6a87d',
    backgroundColor: '#f0e4d2',
    marginTop: 8,
  },
  secondaryButtonLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3b2a15',
  },
  passageContinueButton: {
    marginTop: 16,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#3b2a15',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  passageContinueButtonLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fffaf3',
  },
  blockWrapper: {
    marginBottom: 18,
  },
  shareActionChip: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f0e4d2',
    marginTop: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reflectionModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(43, 27, 10, 0.65)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  reflectionModalCard: {
    backgroundColor: '#fffdf8',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  reflectionModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c1f0c',
    marginBottom: 4,
  },
  reflectionModalMeta: {
    fontSize: 14,
    color: '#6f5a35',
    marginBottom: 16,
  },
  reflectionModalPassageLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6f5a35',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  reflectionModalPassageScroll: {
    maxHeight: 180,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6d9c4',
    backgroundColor: '#fffaf3',
    marginBottom: 16,
  },
  reflectionModalPassageContent: {
    padding: 12,
  },
  reflectionModalPassageText: {
    fontSize: 15,
    lineHeight: 24,
    color: '#3b2a15',
  },
  reflectionModalInput: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 96,
    fontSize: 15,
    color: '#3b2a15',
  },
  reflectionModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 16,
  },
  reflectionModalButtonSecondary: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#ffffff',
    marginRight: 12,
  },
  reflectionModalButtonSecondaryLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6f5a35',
  },
  reflectionModalButtonPrimary: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: '#6d9c7c',
    borderWidth: 1,
    borderColor: '#598467',
  },
  reflectionModalButtonPrimaryLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },
  actionChipRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  chipInRow: {
    alignSelf: 'auto',
  },
  chipSpacing: {
    marginLeft: 12,
  },
  sectionPagerList: {
    flexGrow: 1,
    flex: 1,
  },
  sectionPagerContent: {
    paddingHorizontal: 0,
  },
  sectionPagerWrapper: {
    flex: 1,
    width: '100%',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  sectionPagerItem: {
    flex: 1,
    flexShrink: 0,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  sectionPagerScrollView: {
    flex: 1,
  },
  sectionPagerScroll: {
    paddingBottom: 16,
  },
  sectionPassageContent: {
    paddingBottom: 12,
    flex: 1,
  },
  sectionPassageCard: {
    flex: 1,
    marginBottom: 0,
  },
  sectionPagerIndicator: {
    alignSelf: 'flex-start',
    backgroundColor: '#f0e4d2',
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginBottom: 18,
  },
  sectionPagerIndicatorLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6f5a35',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  sectionPagerBlock: {
    paddingBottom: 12,
  },
  sectionPagerFooter: {
    paddingTop: 8,
  },
  sectionEmptyText: {
    paddingHorizontal: 20,
  },
  settingsGroup: {
    marginTop: 16,
  },
  settingsGroupLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6f5a35',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  settingsOption: {
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: '#f7f0e3',
    marginBottom: 12,
  },
  settingsOptionSelected: {
    borderColor: '#c6a87d',
    backgroundColor: '#f0e4d2',
  },
  settingsOptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsOptionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c1f0c',
  },
  settingsOptionBadge: {
    borderRadius: 10,
    backgroundColor: '#e6d2b5',
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  settingsOptionBadgeLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#3b2a15',
  },
  settingsOptionDescription: {
    fontSize: 14,
    color: '#6f5a35',
    marginTop: 6,
  },
  sharePreviewScroll: {
    flex: 1,
    width: '100%',
  },
  sharePreviewScrollContent: {
    flexGrow: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  sharePreviewWrapper: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  sharePreviewOuter: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 30,
    borderWidth: 2,
    padding: 6,
    backgroundColor: '#fdf8f2',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
    alignSelf: 'center',
    flexShrink: 0,
  },
  sharePreviewOuterMedia: {
    borderColor: 'transparent',
  },
  sharePreviewShot: {
    width: '100%',
    minHeight: 320,
    borderRadius: 24,
    overflow: 'hidden',
    flexShrink: 0,
  },
  sharePreviewCard: {
    width: '100%',
    minHeight: 320,
    borderRadius: 24,
    paddingVertical: 32,
    paddingHorizontal: 28,
    overflow: 'hidden',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
  },
  sharePreviewCardMedia: {
    paddingVertical: 0,
    paddingHorizontal: 0,
    backgroundColor: '#000000',
  },
  sharePreviewMediaWrapper: {
    ...StyleSheet.absoluteFillObject,
  },
  sharePreviewOverlayLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  sharePreviewOverlayContent: {
    ...StyleSheet.absoluteFillObject,
    paddingVertical: 32,
    paddingHorizontal: 28,
    justifyContent: 'space-between',
  },
  sharePreviewVideo: {
    ...StyleSheet.absoluteFillObject,
  },
  sharePreviewImage: {
    borderRadius: 24,
    resizeMode: 'cover',
  },
  sharePreviewAccent: {
    position: 'absolute',
    top: -140,
    right: -40,
    width: 240,
    height: 240,
    borderRadius: 160,
    opacity: 0.18,
    zIndex: 0,
  },
  sharePreviewAccentSecondary: {
    position: 'absolute',
    bottom: -160,
    left: -60,
    width: 280,
    height: 280,
    borderRadius: 180,
    opacity: 0.12,
    zIndex: 0,
  },
  sharePreviewContent: {
    flex: 1,
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    zIndex: 1,
  },
  sharePreviewBody: {
    width: '100%',
    flexShrink: 1,
  },
  sharePreviewQuote: {
    width: '100%',
    fontSize: 20,
    lineHeight: 32,
    fontWeight: '500',
    flexShrink: 1,
    marginBottom: 12,
  },
  sharePreviewAttribution: {
    marginTop: 24,
    width: '100%',
  },
  sharePreviewDivider: {
    width: 48,
    height: 2,
    opacity: 0.35,
    marginBottom: 12,
  },
  sharePreviewAuthor: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: 10,
    marginBottom: 4,
  },
  sharePreviewSection: {
    fontSize: 14,
    opacity: 0.9,
  },
  sharePreviewFooter: {
    paddingTop: 16,
    zIndex: 1,
    alignItems: 'center',
  },
  sharePreviewFooterLine: {
    width: '100%',
    height: 1,
    opacity: 0.3,
    marginBottom: 10,
  },
  sharePreviewFooterLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  shareSelectStage: {
    flex: 1,
  },
  shareSelectHelper: {
    color: '#6f5a35',
    marginBottom: 16,
  },
  shareSelectionInfoRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  shareSelectionSourceLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#3b2a15',
  },
  shareSelectionSection: {
    fontSize: 14,
    color: '#6f5a35',
    marginLeft: 12,
    marginTop: 4,
  },
  shareSelectList: {
    flex: 1,
    marginBottom: 12,
  },
  shareSelectListContent: {
    paddingBottom: 16,
  },
  shareSelectionPassage: {
    lineHeight: 28,
  },
  shareSentenceText: {
    paddingVertical: 2,
    paddingHorizontal: 4,
    borderRadius: 6,
  },
  shareSentenceTextSelected: {
    backgroundColor: '#f2e6d4',
  },
  shareSelectionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  shareSelectionCount: {
    fontSize: 13,
    color: '#6f5a35',
  },
  shareNextButton: {
    minWidth: 132,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 999,
    backgroundColor: '#c6a87d',
    borderWidth: 1,
    borderColor: '#b18d5c',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareNextButtonDisabled: {
    backgroundColor: '#e5d6be',
    borderColor: '#d5c3a5',
  },
  shareNextButtonLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  shareEditorContainer: {
    flex: 1,
  },
  shareEditorBody: {
    flex: 1,
  },
  sharePalette: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f8f2e7',
    padding: 16,
    marginBottom: 16,
  },
  sharePaletteTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
    marginBottom: 12,
  },
  sharePaletteTab: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#efe2ce',
    marginHorizontal: 4,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sharePaletteTabActive: {
    backgroundColor: '#c6a87d',
    borderColor: '#b18d5c',
  },
  sharePaletteTabIcon: {
    textAlign: 'center',
  },
  shareEditorFooter: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 16,
  },
  shareToolbar: {
    flex: 1,
    minWidth: 0,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#f8f2e7',
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  shareToolbarTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
    marginBottom: 8,
  },
  shareToolbarContent: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingVertical: 8,
    paddingHorizontal: 6,
    minHeight: 96,
  },
  sharePaletteContent: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingVertical: 10,
    paddingHorizontal: 8,
    minHeight: 140,
    maxHeight: 220,
  },
  shareMediaPanel: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  shareCaptureButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#c6a87d',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#b18d5c',
  },
  shareCaptureButtonDisabled: {
    opacity: 0.6,
  },
  shareCaptureButtonIcon: {
    marginRight: 8,
  },
  shareCaptureButtonLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#ffffff',
  },
  shareCaptureNotice: {
    fontSize: 13,
    color: '#6f5a35',
    marginBottom: 12,
  },
  shareCapturePreview: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#fdf8f2',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  shareCapturePreviewIcon: {
    marginRight: 10,
  },
  shareCapturePreviewInfo: {
    flex: 1,
  },
  shareCaptureFileLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3b2a15',
  },
  shareCaptureFileMeta: {
    fontSize: 12,
    color: '#6f5a35',
    marginTop: 2,
  },
  shareCaptureResetButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c6a87d',
    backgroundColor: '#ffffff',
  },
  shareCaptureResetLabel: {
    fontSize: 13,
    color: '#6f5a35',
    fontWeight: '600',
  },
  sharePaletteScroll: {
    maxHeight: 200,
  },
  sharePaletteScrollContent: {
    paddingBottom: 12,
  },
  sharePaletteChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 4,
    paddingVertical: 4,
    rowGap: 8,
    columnGap: 8,
  },
  sharePaletteChip: {
    marginBottom: 0,
    marginRight: 8,
  },
  sharePaletteOptionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingVertical: 4,
    paddingHorizontal: 6,
    columnGap: 8,
    rowGap: 12,
    justifyContent: 'flex-start',
  },
  sharePaletteCompactOption: {
    width: 68,
    marginHorizontal: 4,
    marginBottom: 4,
    alignItems: 'center',
  },
  sharePaletteCompactSwatch: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#fffdf8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sharePaletteCompactSwatchSelected: {
    borderColor: '#c6a87d',
    backgroundColor: '#f2e6d4',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  sharePaletteCompactLabel: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: '500',
    color: '#6f5a35',
    textAlign: 'center',
  },
  sharePaletteCompactLabelActive: {
    color: '#3b2a15',
  },
  sharePaletteFontSample: {
    fontSize: 18,
    fontWeight: '700',
    color: '#3b2a15',
  },
  sharePaletteBackgroundChip: {
    width: 32,
    height: 32,
    borderRadius: 10,
    borderWidth: 2,
  },
  sharePaletteLayoutGlyph: {
    width: '100%',
    height: '100%',
    alignItems: 'stretch',
    justifyContent: 'center',
  },
  sharePaletteLayoutLine: {
    height: 3,
    borderRadius: 2,
    backgroundColor: '#3b2a15',
    marginVertical: 1,
  },
  sharePaletteLayoutLinePoster: {
    height: 4,
  },
  sharePaletteSwatchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  sharePaletteColorSwatch: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginHorizontal: 6,
    marginBottom: 8,
  },
  sharePaletteLayoutRow: {
    flexDirection: 'row',
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  shareThemeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginVertical: 4,
    marginHorizontal: -4,
  },
  shareEditorScroll: {
    paddingBottom: 36,
  },
  shareEditorSection: {
    marginBottom: 24,
  },
  shareEditorLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3b2a15',
    marginBottom: 12,
  },
  shareThemeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    marginHorizontal: 4,
    marginBottom: 8,
  },
  shareThemeChipSelected: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  shareThemeSwatch: {
    width: 18,
    height: 18,
    borderRadius: 9,
    marginRight: 10,
  },
  shareThemeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3b2a15',
  },
  shareEditorColorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  shareEditorColorSwatch: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginHorizontal: 4,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  shareEditorColorSwatchSelected: {
    borderColor: '#c6a87d',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  shareEditorBackgroundPreview: {
    width: '100%',
    height: 48,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#d7c5a8',
    marginBottom: 6,
  },
  shareEditorOptionsColumn: {
    flexDirection: 'column',
  },
  shareEditorHelperText: {
    fontSize: 13,
    color: '#6f5a35',
    marginBottom: 12,
  },
  shareSegmentList: {
    flexDirection: 'column',
  },
  shareSegmentCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: '#d7c5a8',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#ffffff',
    marginBottom: 12,
  },
  shareSegmentCardSelected: {
    borderColor: '#c6a87d',
    backgroundColor: '#f7ecda',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  shareSegmentBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#c6a87d',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  shareSegmentBadgeLabel: {
    color: '#ffffff',
    fontWeight: '700',
  },
  shareSegmentPreview: {
    flex: 1,
    fontSize: 14,
    color: '#3b2a15',
    lineHeight: 20,
  },
  shareNowButton: {
    alignSelf: 'center',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 18,
    backgroundColor: '#c6a87d',
    borderWidth: 1,
    borderColor: '#b18d5c',
  },
  shareNowButtonLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  shareFloatingButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#c6a87d',
    borderWidth: 1,
    borderColor: '#b18d5c',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  shareFloatingButtonDisabled: {
    backgroundColor: '#e5d6be',
    borderColor: '#d5c3a5',
    opacity: 0.5,
  },
  shareDestinationBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  shareDestinationDismiss: {
    ...StyleSheet.absoluteFillObject,
  },
  shareDestinationSheet: {
    backgroundColor: '#fdf8f2',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 32,
    borderTopWidth: 1,
    borderColor: '#d7c5a8',
  },
  shareDestinationTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#3b2a15',
    marginBottom: 16,
  },
  shareDestinationOptions: {
    flexDirection: 'column',
    marginBottom: 12,
  },
  shareDestinationOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e6d9c4',
  },
  shareDestinationOptionIcon: {
    marginRight: 12,
  },
  shareDestinationOptionLabel: {
    fontSize: 15,
    color: '#3b2a15',
    fontWeight: '600',
  },
  shareDestinationCancel: {
    marginTop: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7c5a8',
    backgroundColor: '#ffffff',
  },
  shareDestinationCancelLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#6f5a35',
  },
  contentScroll: {
    paddingBottom: 40,
  },
  contentTitle: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 12,
    color: '#2c1f0c',
  },
  sectionDetailTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 16,
    color: '#3b2a15',
  },
  contentHeading: {
    fontSize: 18,
    fontWeight: '600',
    marginTop: 18,
    marginBottom: 4,
    color: '#000000',
  },
  contentHeadingFirst: {
    marginTop: 0,
  },
  contentParagraph: {
    fontSize: 16,
    lineHeight: 26,
    color: '#111111',
    marginTop: 4,
    marginBottom: 12,
  },
  contentParagraphFirst: {
    marginTop: 0,
  },
  blockContainer: {
    marginBottom: 16,
  },
  quoteBlock: {
    borderLeftWidth: 3,
    borderLeftColor: '#d7c5a8',
    paddingLeft: 12,
    marginTop: 12,
    marginBottom: 16,
  },
  quoteText: {
    fontSize: 16,
    lineHeight: 26,
    fontStyle: 'italic',
    color: '#111111',
  },
  poetryBlock: {
    marginTop: 12,
    marginBottom: 16,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: '#d7c5a8',
  },
  poetryLine: {
    fontSize: 16,
    lineHeight: 24,
    color: '#111111',
  },
  listBlock: {
    marginTop: 8,
    marginBottom: 16,
    paddingLeft: 16,
  },
  listItemText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#111111',
    marginBottom: 4,
  },
  passageNumber: {
    color: '#000000',
    fontWeight: '700',
  },
  firstBlock: {
    marginTop: 0,
  },
  footnoteContainer: {
    marginTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#d7c5a8',
    paddingTop: 10,
  },
  footnoteText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#2e2e2e',
    marginTop: 4,
  },
  attributionText: {
    fontSize: 15,
    lineHeight: 24,
    fontStyle: 'italic',
    color: '#1f1f1f',
    textAlign: 'right',
    marginTop: 12,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  emptyStateText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#6f5a35',
  },
});
